[[d1_databases]]
binding = "DATABASE"
database_name = "cf-nextjs-test-db"
database_id = "fa5666af-6aa6-457b-85f8-0fa96ebcbf82"
migrations_dir = "./drizzle"

[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "cf-nextjs-test-bucket"
